version: '3'

services:
  db:
    image: mysql
    ports:
        - "13306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  web:
    environment:
        SPRING_JPA_HIBERNATE_DDL-AUTO: create
