version: '3'

services:
  web:
    image: com.technology/cicdpoc-app
    volumes:
     - ./logs:/app/logs
    ports:
      - "9090:8080"
    entrypoint: ["./wait-for-it.sh","db:3306","--timeout=0","--strict", "--", "java","-Xms1024m","-Xmx2048m", "-Djava.security.egd=file:/dev/./urandom", "-jar","app.jar" ]
    environment:
        SPRING_JPA_HIBERNATE_DDL-AUTO: none
        SPRING_PROFILES_ACTIVE: docker
        LOG_DIRECTORY: /app/logs
        AWS_IP: ${AWS_IP}
    depends_on:
      - db


  db:
      image: mysql
      ports:
        - "13306:3306"
      volumes:
        - ./data:/var/lib/mysql
      environment:
          MYSQL_ROOT_PASSWORD:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_DATABASE: efsdev

